language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cddbase' ]; then cd .. && eval "mv $currentfolder generator-cddbase" && cd generator-cddbase; fi

